CREATE TABLE IF NOT EXISTS MARCAS (
    marca_id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS MODELOS (
    modelo_id INTEGER PRIMARY KEY AUTOINCREMENT,
    marca_id INTEGER NOT NULL,
    nome VARCHAR(50) NOT NULL,
    FOREIGN KEY (marca_id) REFERENCES MARCAS(marca_id)
);

CREATE TABLE IF NOT EXISTS MOTORES (
    motor_id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS MODELOS_MOTORES (
    modelo_motor_id INTEGER PRIMARY KEY AUTOINCREMENT,
    modelo_id INTEGER NOT NULL,
    motor_id INTEGER NOT NULL,
    ano_inicio INTEGER NOT NULL,
    ano_fim INTEGER NOT NULL,
    FOREIGN KEY (modelo_id) REFERENCES MODELOS(modelo_id),
    FOREIGN KEY (motor_id) REFERENCES MOTORES(motor_id)
);

CREATE TABLE IF NOT EXISTS ESPECIFICACOES_OLEO (
    oleo_id INTEGER PRIMARY KEY AUTOINCREMENT,
    motor_id INTEGER NOT NULL,
    viscosidade VARCHAR(6) NOT NULL,
    norma_api VARCHAR(50) NOT NULL,
    norma_acea VARCHAR(50) NOT NULL,
    capacidade_litros DECIMAL(4,2) NOT NULL,
    observacoes TEXT NOT NULL,
    FOREIGN KEY (motor_id) REFERENCES MOTORES(motor_id)
);

CREATE TABLE IF NOT EXISTS FILTROS (
    filtro_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tipo TEXT NOT NULL CHECK(tipo IN ('blindado', 'refil')),
    marca VARCHAR(50) NOT NULL,
    numero_peca VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS MOTOR_FILTROS (
    motor_filtro_id INTEGER PRIMARY KEY AUTOINCREMENT,
    modelo_motor_id INTEGER NOT NULL,
    filtro_id INTEGER NOT NULL,
    FOREIGN KEY (modelo_motor_id) REFERENCES MODELOS_MOTORES(modelo_motor_id),
    FOREIGN KEY (filtro_id) REFERENCES FILTROS(filtro_id)
);
