CREATE TABLE IF NOT EXISTS MARCAS (
    marca_id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS MODELOS (
    modelo_id INTEGER PRIMARY KEY AUTOINCREMENT,
    marca_id INTEGER NOT NULL,
    nome VARCHAR(50) NOT NULL,
    FOREIGN KEY (marca_id) REFERENCES MARCAS(marca_id)
);

CREATE TABLE IF NOT EXISTS MOTORES (
    motor_id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS MODELOS_MOTORES (
    modelo_motor_id INTEGER PRIMARY KEY AUTOINCREMENT,
    modelo_id INTEGER NOT NULL,
    motor_id INTEGER NOT NULL,
    ano_inicio INTEGER NOT NULL,
    ano_fim INTEGER NOT NULL,
    FOREIGN KEY (modelo_id) REFERENCES MODELOS(modelo_id),
    FOREIGN KEY (motor_id) REFERENCES MOTORES(motor_id)
);

CREATE TABLE IF NOT EXISTS ESPECIFICACOES_OLEO (
    oleo_id INTEGER PRIMARY KEY AUTOINCREMENT,
    modelo_motor_id INTEGER NOT NULL,
    viscosidade VARCHAR(6),
    norma_api VARCHAR(50),
    norma_acea VARCHAR(50),
    capacidade_litros DECIMAL(4,2),
    observacoes TEXT,
    FOREIGN KEY (modelo_motor_id) REFERENCES MODELOS_MOTORES(modelo_motor_id)
);

CREATE TABLE IF NOT EXISTS FILTROS (
    filtro_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tipo TEXT NOT NULL CHECK(tipo IN ('blindado', 'refil')),
    marca VARCHAR(50) NOT NULL,
    numero_peca VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS MOTOR_FILTROS (
    motor_filtro_id INTEGER PRIMARY KEY AUTOINCREMENT,
    modelo_motor_id INTEGER NOT NULL,
    filtro_id INTEGER NOT NULL,
    FOREIGN KEY (modelo_motor_id) REFERENCES MODELOS_MOTORES(modelo_motor_id),
    FOREIGN KEY (filtro_id) REFERENCES FILTROS(filtro_id)
);

CREATE TABLE IF NOT EXISTS SERVICE_LOGS (
    logs_id INTEGER PRIMARY KEY AUTOINCREMENT,

    placa VARCHAR(10),
    oleo_utilizado VARCHAR(10) NOT NULL,

    oleo_trocado BOOLEAN NOT NULL DEFAULT false,
    filtro_trocado BOOLEAN NOT NULL DEFAULT false,
    tampa_ok BOOLEAN NOT NULL DEFAULT false,
    luz_oleo_ok BOOLEAN NOT NULL DEFAULT false,
    vazamento_ok BOOLEAN NOT NULL DEFAULT false,
    nivel_oleo_ok BOOLEAN NOT NULL DEFAULT false,
    etiqueta_ok BOOLEAN NOT NULL DEFAULT false,
    sobra_oleo_ok BOOLEAN NOT NULL DEFAULT false,

    observacoes TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
