CREATE TABLE IF NOT EXISTS MARCAS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS MODELOS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    marca_id INTEGER NOT NULL,
    nome TEXT NOT NULL,
    FOREIGN KEY (marca_id) REFERENCES MARCAS(id)
);

CREATE TABLE IF NOT EXISTS MOTORES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome_motor TEXT NOT NULL,
    ano_inicio INTEGER,
    ano_fim INTEGER
);

CREATE TABLE IF NOT EXISTS MODELOS_MOTORES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    modelo_id INTEGER NOT NULL,
    motor_id INTEGER NOT NULL,
    FOREIGN KEY (modelo_id) REFERENCES MODELOS(id),
    FOREIGN KEY (motor_id) REFERENCES MOTORES(id)
);

CREATE TABLE IF NOT EXISTS ESPECIFICACOES_OLEO (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    motor_id INTEGER NOT NULL,
    viscosidade TEXT,
    especificacao TEXT,
    capacidade_litros REAL,
    FOREIGN KEY (motor_id) REFERENCES MOTORES(id)
);

CREATE TABLE IF NOT EXISTS FILTROS_OEM (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tipo TEXT NOT NULL CHECK(tipo IN ('Blindado', 'Refil')),
    marca TEXT,
    numero_peca TEXT
);

CREATE TABLE IF NOT EXISTS MOTORES_FILTROS_OEM (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    motor_id INTEGER NOT NULL,
    filtro_oem_id INTEGER NOT NULL,
    FOREIGN KEY (motor_id) REFERENCES MOTORES(id),
    FOREIGN KEY (filtro_oem_id) REFERENCES FILTROS_OEM(id)
);

CREATE TABLE IF NOT EXISTS FILTROS_EQUIVALENTES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    marca TEXT,
    numero_peca TEXT
);

CREATE TABLE IF NOT EXISTS OEM_FILTROS_EQUIVALENTES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    filtro_oem_id INTEGER NOT NULL,
    filtro_equivalente_id INTEGER NOT NULL,
    FOREIGN KEY (filtro_oem_id) REFERENCES FILTROS_OEM(id),
    FOREIGN KEY (filtro_equivalente_id) REFERENCES FILTROS_EQUIVALENTES(id)
);
